version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: jotamatera_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # La misma password que pusiste en Nest
      MYSQL_DATABASE: JOTAMATERA_DB # La BD se crea sola con este nombre
    ports:
      - "4013:3306" # ¡Aca está la magia de los puertos que hablábamos!
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: