version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: jotamatera_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-JOTAMATERA_DB}
    ports:
      - "${DB_PORT:-4013}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: